/* Auth */
export const SET_LOGGED_IN = 'AUTH/SET_LOGGED_IN';
export const SET_LOGGED_OUT = 'AUTH/SET_LOGGED_OUT';

/* Messages */
export const SET_SHOULD_SCROLL_TO_BOTTOM = 'MESSAGES/SET_SHOULD_SCROLL_TO_BOTTOM';
export const SET_SHOULD_UPDATE_ROOM = 'MESSAGES/SET_SHOULD_UPDATE_ROOM';
