/* Auth */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const SET_LOGIN_MODAL_OPEN = 'SET_LOGIN_MODAL_OPEN';
export const SET_SIGNUP_MODAL_OPEN = 'SET_SIGNUP_MODAL_OPEN';
export const SET_LOGIN_SUBMIT_ERROR = 'SET_LOGIN_SUBMIT_ERROR';
export const SET_SIGNUP_SUBMIT_ERROR = 'SET_SIGNUP_SUBMIT_ERROR';
export const CLEAR_SUBMIT_ERRORS = 'CLEAR_SUBMIT_ERRORS';
