/* Auth */
export const SET_LOGGED_IN = 'AUTH/SET_LOGGED_IN';
export const SET_LOGGED_OUT = 'AUTH/SET_LOGGED_OUT';
export const SET_LOGIN_MODAL_OPEN = 'AUTH/SET_LOGIN_MODAL_OPEN';
export const SET_SIGNUP_MODAL_OPEN = 'AUTH/SET_SIGNUP_MODAL_OPEN';
export const SET_LOGIN_SUBMIT_ERROR = 'AUTH/SET_LOGIN_SUBMIT_ERROR';
export const SET_SIGNUP_SUBMIT_ERROR = 'AUTH/SET_SIGNUP_SUBMIT_ERROR';
export const CLEAR_AUTH_SUBMIT_ERRORS = 'AUTH/CLEAR_SUBMIT_ERRORS';

/* Comments */
export const SET_SHOULD_SCROLL_TO_BOTTOM = 'COMMENTS/SET_SHOULD_SCROLL_TO_BOTTOM';
